### ISSUE TITLE
Null Pointer Exception : Azure login with personal microsoft accounts added as a guest user in azure portal gives null pointer exception

### ISSUE THREAD

**Issue by SudipAtlas** [wrobins/cordova-plugin-msal#116]
FATAL EXCEPTION: main
                                                                                                    Process: com.***********.************, PID: 16160
                                                                                                    java.lang.NullPointerException
                                                                                                    	at java.util.Objects.requireNonNull(Objects.java:207)
                                                                                                    	at com.wrobins.cordova.plugin.MsalPlugin.getAccountObject(MsalPlugin.java:581)
                                                                                                    	at com.wrobins.cordova.plugin.MsalPlugin.getAuthResult(MsalPlugin.java:568)
                                                                                                    	at com.wrobins.cordova.plugin.MsalPlugin.access$1500(MsalPlugin.java:47)
                                                                                                    	at com.wrobins.cordova.plugin.MsalPlugin$6$1.onSuccess(MsalPlugin.java:416)
                                                                                                    	at com.microsoft.identity.client.PublicClientApplication.postAuthResult(PublicClientApplication.java:2351)
                                                                                                    	at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onTaskCompleted(SingleAccountPublicClientApplication.java:443)
                                                                                                    	at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onTaskCompleted(SingleAccountPublicClientApplication.java:434)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:650)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:99)
                                                                                                    	at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:626)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:240)
                                                                                                    	at android.os.Looper.loop(Looper.java:351)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8377)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by SudipAtlas** [comment]
found the claims in account object is null 
acct.put("claims", processClaims(Objects.requireNonNull(account.getClaims()))); but the claims object can be null
 /**
     * Gets the claims associated to this Account's IdToken. In the case of the Microsoft Identity
     * Platform, this value can be null if the home tenant has not been authorized.
     *
     * @return The claims for this Account's IdToken or null, if no IdToken exists.
     */
    @Nullable
    @Override
    public Map<String, ?> getClaims() {
        return mIdTokenClaims;
    }
