### ISSUE TITLE
Getting error in the time on App compilation

### ISSUE THREAD

**Issue by Neotrixsx** [wrobins/cordova-plugin-msal#36]
I used cordova-plugin-msal in my Android Application, When I try to compile my Android application for testing on that time I get an error:

`:app:processDebugManifest UP-TO-DATE
:app:splitsDiscoveryTaskDebug UP-TO-DATE
:app:processDebugResourcesC:\Users\test\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.2.aar\fc9fe9b92c142495ba79e017cf18ca94\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

C:\WebContent\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

C:\Users\test\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\9d7a7dfeba2eb16cae5bc7d90fa05488\res\values\values.xml:251:5-69: AAPT: error: resource android:attr/fontVariationSettings not found.

C:\Users\test\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\9d7a7dfeba2eb16cae5bc7d90fa05488\res\values\values.xml:251:5-69: AAPT: error: resource android:attr/ttcIndex not found.

Exception in thread "stderr" java.util.UnknownFormatConversionException: Conversion = 'P'
        at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
        at java.util.Formatter.parse(Formatter.java:2560)
        at java.util.Formatter.format(Formatter.java:2501)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at com.android.build.gradle.internal.aapt.AaptGradleFactory$FilteringLogger.shouldDowngrade(AaptGradleFactory.java:178)
        at com.android.build.gradle.internal.aapt.AaptGradleFactory$FilteringLogger.error(AaptGradleFactory.java:144)
        at com.android.ide.common.process.LoggedProcessOutputHandler.handleOutput(LoggedProcessOutputHandler.java:44)
        at com.android.ide.common.process.TeeProcessOutputHandler.handleOutput(TeeProcessOutputHandler.java:59)
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:457)
        at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:415)
        at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
        at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)
`

**Comment by wrobins** [comment]
Hello, and sorry for the trouble you're having.

I've never seen this issue before, but let's try to isolate it. What happens if you create a blank project in your platform (whatever it is, be it vanilla Cordova or Ionic, React, Phonegap, etc) and install only this plugin? Does the issue still occur, or does the exact error change?
